### ISSUE TITLE
Old Rubies on M3 - using RVM

### ISSUE THREAD

**Issue by satyakampandya** [basecamp/ruby-dev#2]
Hi @jeremy,

Thank you for this repository, it's been incredibly helpful!

I've been struggling to install Ruby 2.7.8 on my MacBook Pro M3 using RVM, and I came across a solution [here](https://medium.com/@nelliemckesson/install-ruby-with-rvm-on-an-m3-pro-mac-784718bdb72a), but it requires installing Homebrew in /usr/local under Rosetta Mode. I'm trying to avoid this approach because brew doctor suggests keeping Homebrew in /opt/homebrew for native ARM installations.

Could you suggest a best practice for installing older versions of Ruby on the M3 using RVM without using Rosetta Mode, while keeping Homebrew in its preferred location?

**Comment by jeremy** [comment]
I'd get familiar with RVM's build process and try a custom build using the approaches seen here for ruby-build. Good one to feed to ChatGPT etc!
